### ISSUE TITLE
Missing voucher code attribute

### ISSUE THREAD

**Issue by p0wertiger** [tradetracker-com/tradetracker-gtm-tracking-template#2]
The implementation lacks Voucher Code variable, as explained here:

https://sc.tradetracker.net/implementation/overview?f%5Btarget%5D=merchant&f%5Bname%5D=General&f%5Bversion%5D=All&f%5BversionInfo%5D=Exclusive+voucher+codes&f%5Blimit%5D=25

**Comment by samoneilll** [comment]
Hi there, 

Sorry about the slow reply. This issue should be resolved in a new version that we will deploy to the community gallery later this week.

**Comment by samoneilll** [comment]
This should now be solved with version 409...a6b that is now available through the community template gallery.
